### 📌 Crear un usuario
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Robert",
  "email": "robert@example.com",
  "password": "c"
}

### 📌 Crear un usuario
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Lilia",
  "email": "lili@example.com",
  "password": "Hola0510"
}

### INICIAR SESIÓN
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "robert@example.com",
  "password": "YaporfavorDorx"
}


### CREAR ANIME CON IMAGEN Y EPISODIOS
POST http://localhost:3000/api/animes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWQzNWIyOWIxYmI0NWQwMzRiYTY5YSIsImlhdCI6MTc0Njc0NDc3MiwiZXhwIjoxNzQ2NzQ4MzcyfQ.7H2KdgQBa_kSB1nDIOQvK5eqjcLqEUmFqDV0KeqTuBA
Content-Type: multipart/form-data; boundary=FormBoundary

--FormBoundary
Content-Disposition: form-data; name="title"

Naruto
--FormBoundary
Content-Disposition: form-data; name="description"

Un anime legendario
--FormBoundary
Content-Disposition: form-data; name="file"; filename="katyusha 4.png"
Content-Type: image/png

< D:\imagenes\katyusha 4.png
--FormBoundary--

### SUBIR EPISODIO CON VIDEO
POST http://localhost:3000/episodes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWQ3Yzk3YjhlNzU3MjAzMGQ3YTZkNCIsImlhdCI6MTc0NzEwMTc0OCwiZXhwIjoxNzQ3MTA1MzQ4fQ.7ix9woJTnTFskSZc87pduZfx1CJDv94DOPv34NEImP4
Content-Type: multipart/form-data; boundary=FormBoundary

--FormBoundary
Content-Disposition: form-data; name="title"

Capítulo 1: El inicio
--FormBoundary
Content-Disposition: form-data; name="number"

1
--FormBoundary
Content-Disposition: form-data; name="anime"

682281d68ec50b91f2008653
--FormBoundary
Content-Disposition: form-data; name="file"; filename="Episodio 1.mp4"
Content-Type: video/mp4

< C:\Users\rober\Downloads\Episodio 1.mp4
--FormBoundary--


### AGREGAR O QUITAR FAVORITO
PATCH http://localhost:3000/api/users/favoritos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWQzNWIyOWIxYmI0NWQwMzRiYTY5YSIsImlhdCI6MTc0Njc0ODkxNywiZXhwIjoxNzQ2NzUyNTE3fQ.x8axFANqbRLDOYi4F-TW8RiXyPa3mTflKyRoxN3HvkE
Content-Type: application/json

{
  "animeId": "681d3c8158bb04e2835eaaa6"
}

### SEGUIR O DEJAR DE SEGUIR UN USUARIO
PATCH http://localhost:3000/api/users/follow
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWQzNWIyOWIxYmI0NWQwMzRiYTY5YSIsImlhdCI6MTc0Njc0ODkxNywiZXhwIjoxNzQ2NzUyNTE3fQ.x8axFANqbRLDOYi4F-TW8RiXyPa3mTflKyRoxN3HvkE
Content-Type: application/json

{
  "targetUserId": "681d46453e707d8d82f6f4e7"
}
